import { InputElement } from "./core/InputElement.js";
import type { IInputElement } from "./core/IInputElement.js";
export declare type InputTimeValue = {
    hours: number;
    minutes: number;
    seconds: number;
    miliseconds: number;
};
export declare class InputTimeElement extends InputElement<InputTimeValue> implements IInputElement<InputTimeValue> {
    private static regexp;
    readonly emptyValue: InputTimeValue;
    defaultValue: InputTimeValue;
    value: InputTimeValue;
    disabled: boolean;
    readOnly: boolean;
    autofocus: boolean;
    precision: number;
    private _hours;
    private _minutes;
    private _seconds;
    private _miliseconds;
    private _evaluateInput;
    private _onInputHours;
    private _onInputMinutes;
    private _onInputSeconds;
    private _onInputMiliseconds;
    private _onBlurHours;
    private _onBlurMinutes;
    private _onBlurSeconds;
    private _onBlurMiliseconds;
    private _updateIU;
    private _updateUIHours;
    private _updateUIMinutes;
    private _updateUISeconds;
    private _updateUIMiliseconds;
    private _onClearValue;
    private _updateValue;
    clearValue(): void;
    hasSameValueAs(value: InputTimeValue): boolean;
    focus(): void;
    blur(): void;
    render(): import("lit-html").TemplateResult<1>;
    static styles: import("lit").CSSResultGroup;
}
